[terminal]
[terminal.shell]
  program = "/bin/zsh"
  # args = ["-c","fastfetch"]

[window]
opacity = 0.2
padding = { x = 5, y = 5 }
dynamic_padding = true
title = "terminal"
class = {instance = "terminal", general = "terminal"}

[font]
normal = { family = "monospace", style = "Regular" } # default
size = 11

[colors.primary]
background = "#151515"
foreground = "#a1b0b8"

[colors.normal]
black   = "#252525"
red     = "#832e31"
green   = "#a63c40"
yellow  = "#d3494e"
blue    = "#fc595f"
magenta = "#df9395"
cyan    = "#ba8586"
white   = "#f5f5f5"

[colors.bright]
black   = "#5d6f71"
red     = "#832e31"
green   = "#a63c40"
yellow  = "#d2494e"
blue    = "#fc595f"
magenta = "#df9395"
cyan    = "#ba8586"
white   = "#f5f5f5"

[colors.cursor]
text = "#708284"
cursor = "#ff443e"

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = {shape= "beam", blinking = "Never"}
unfocused_hollow = false

